<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Major Neural Network Architectures Challenge
## *Data Science Unit 4 Sprint 3 Challenge*

In this sprint challenge, you'll explore some of the cutting edge of Data Science. This week we studied several famous neural network architectures: 
recurrent neural networks (RNNs), long short-term memory (LSTMs), convolutional neural networks (CNNs), and Generative Adverserial Networks (GANs). In this sprint challenge, you will revisit these models. Remember, we are testing your knowledge of these architectures not your ability to fit a model with high accuracy. 

__*Caution:*__  these approaches can be pretty heavy computationally. All problems were designed so that you should be able to achieve results within at most 5-10 minutes of runtime on Colab or a comparable environment. If something is running longer, doublecheck your approach!

## Challenge Objectives
*You should be able to:*
* <a href="#p1">Part 1</a>: Train a RNN classification model
* <a href="#p2">Part 2</a>: Utilize a pre-trained CNN for objective detection
* <a href="#p3">Part 3</a>: Describe the components of an autoencoder
* <a href="#p4">Part 4</a>: Describe yourself as a Data Science and elucidate your vision of AI

<a id="p1"></a>
## Part 1 - RNNs

Use an RNN/LSTM to fit a multi-class classification model on reuters news articles to distinguish topics of articles. The data is already encoded properly for use in an RNN model. 

Your Tasks: 
- Use Keras to fit a predictive model, classifying news articles into topics. 
- Report your overall score and accuracy

For reference, the [Keras IMDB sentiment classification example](https://github.com/keras-team/keras/blob/master/examples/imdb_lstm.py) will be useful, as well the RNN code we used in class.

__*Note:*__  Focus on getting a running model, not on maxing accuracy with extreme data size or epoch numbers. Only revisit and push accuracy if you get everything else done!

In [25]:
from tensorflow.keras.datasets import reuters

(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=None,
                                                         skip_top=0,
                                                         maxlen=None,
                                                         test_split=0.2,
                                                         seed=723812,
                                                         start_char=1,
                                                         oov_char=2,
                                                         index_from=3)

In [26]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(8982,) (8982,) (2246,) (2246,)


In [27]:
# Demo of encoding

word_index = reuters.get_word_index(path="reuters_word_index.json")

print(f"Iran is encoded as {word_index['iran']} in the data")
print(f"London is encoded as {word_index['london']} in the data")
print("Words are encoded as numbers in our dataset.")

Iran is encoded as 779 in the data
London is encoded as 544 in the data
Words are encoded as numbers in our dataset.


In [43]:
word_index.values()

dict_values([10996, 16260, 12089, 8803, 13796, 20672, 20673, 20675, 10997, 8804, 20676, 20677, 8352, 20713, 16261, 185, 1642, 20680, 12090, 1220, 13797, 7593, 20681, 3914, 2563, 3551, 5113, 3552, 3400, 7975, 3401, 3478, 3632, 4309, 9381, 7247, 3086, 20683, 8805, 20684, 16262, 20685, 13798, 20686, 20687, 7972, 20688, 20689, 2891, 20690, 16263, 595, 16264, 3189, 16265, 16266, 20692, 13799, 12092, 3028, 6693, 20693, 12093, 12639, 9382, 4007, 5689, 12094, 7903, 10066, 20695, 20696, 2394, 20697, 13800, 1984, 10998, 6959, 13801, 20698, 8806, 43, 9383, 20813, 16267, 10999, 13802, 20699, 1267, 20700, 3633, 3029, 10067, 13803, 13804, 850, 20701, 16268, 7973, 4677, 6422, 16269, 1858, 16270, 20702, 20703, 16271, 20704, 20705, 20706, 11000, 12095, 20707, 20708, 2461, 20709, 16272, 20711, 16273, 16274, 20712, 16275, 11001, 4205, 16276, 1916, 4819, 6164, 12096, 6165, 8807, 11129, 20714, 20715, 20716, 1788, 13805, 8808, 13806, 20717, 20718, 10089, 11002, 6960, 20719, 3891, 4008, 4206, 3079, 4550, 616

In [44]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

batch_size = 46
max_features = len(word_index.values())
maxlen = 200


# batch_size = 32
# max_features = 20000
# maxlen = 100

print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)


print('Build model...')
# TODO - your code!



8982 train sequences
2246 test sequences
Pad sequences (samples x time)
X_train shape: (8982, 200)
X_test shape: (2246, 200)
Build model...


In [45]:
max_features

30979

In [46]:
len(X_train[0])

200

In [47]:
model = Sequential()
model.add(Embedding(max_features+1, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

In [48]:
# You should only run this cell once your model has been properly configured

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=1,
          validation_data=(X_test, y_test))

score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

Train...
Train on 8982 samples, validate on 2246 samples
8982/8982 [==============================] - 60s 7ms/sample - loss: -189.9606 - accuracy: 0.0492 - val_loss: -300.4297 - val_accuracy: 0.0396
2246/1 [=========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

Test score: -300.4297064002454
Test accuracy: 0.039626002


## Sequence Data Question
#### *Describe the `pad_sequences` method used on the training dataset. What does it do? Why do you need it?*

Please add your answer in markdown here.

## RNNs versus LSTMs
#### *What are the primary motivations behind using Long-ShortTerm Memory Cell unit over traditional Recurrent Neural Networks?*

Please add your answer in markdown here.

## RNN / LSTM Use Cases
#### *Name and Describe 3 Use Cases of LSTMs or RNNs and why they are suited to that use case*

Please add your answer in markdown here.

#### In the case of variable length sequence prediction problems, this requires that data be transformed such that each sequence has the same length.

#### This vectorization allows code to efficiently perform the matrix operations in batch for your chosen deep learning algorithms

#### `pad_sequences` helps to pad 0 to bring to desired sequence length or trim the sequence to desired length

#### primary motivation behind using LSTM over traditional RNNs is to avoid vanishing gradient problem.  traditional RNNs do not remember the initial values of a input sequence and tend to only give weightage to recent input values. LSTM is a way to remember older inputs ina time series sequence, (albeit with lower weights.) 

#### Use cases :
#### Any sequence or time series based classifications or predictions. EG: Text predictions, Text generation, Weather predictions, stock value prediction. 
#### RNN’s (LSTM’s) are pretty good at extracting patterns in input feature space, where the input data spans over long sequences. Given the gated architecture of LSTM’s that has this ability to manipulate its memory state, they are ideal for such problems.

<a id="p2"></a>
## Part 2- CNNs

### Find the Frog

Time to play "find the frog!" Use Keras and ResNet50 (pre-trained) to detect which of the following images contain frogs:

<img align="left" src="https://d3i6fh83elv35t.cloudfront.net/newshour/app/uploads/2017/03/GettyImages-654745934-1024x687.jpg" width=400>


In [49]:
!pip install google_images_download

    100% |████████████████████████████████| 911kB 6.6MB/s ta 0:00:011
  Stored in directory: /Users/karthikmahendra/Library/Caches/pip/wheels/1f/28/ad/f56e7061e1d2a9a1affe2f9c649c2570cb9198dd24ede0bbab
Successfully built google-images-download


In [85]:
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model # This is the functional API

In [51]:
from google_images_download import google_images_download

response = google_images_download.googleimagesdownload()
arguments = {"keywords": "lilly frog pond", "limit": 5, "print_urls": True}
absolute_image_paths = response.download(arguments)


Item no.: 1 --> Item name = lilly frog pond
Evaluating...
Starting Download...
Image URL: http://www.slrobertson.com/images/usa/georgia/atlanta/atl-botanical-gardens/frog-lily-pond-2-b.jpg
Completed Image ====> 1.frog-lily-pond-2-b.jpg
Image URL: https://cdn.pixabay.com/photo/2017/07/14/17/44/frog-2504507_960_720.jpg
Completed Image ====> 2.frog-2504507_960_720.jpg
Image URL: https://www.welcomewildlife.com/wp-content/uploads/2015/01/Frog-on-lily-pad.jpg
Completed Image ====> 3.Frog-on-lily-pad.jpg
Image URL: https://i.pinimg.com/originals/9a/49/08/9a49083d4d7458a194a451eea757a444.jpg
Completed Image ====> 4.9a49083d4d7458a194a451eea757a444.jpg
Image URL: https://www.maxpixel.net/static/photo/1x/Frog-Pond-Lily-Pad-Water-Nature-Animal-4336943.jpg
Completed Image ====> 5.Frog-Pond-Lily-Pad-Water-Nature-Animal-4336943.jpg

Errors: 0



In [68]:
absolute_image_paths[0]

{'lilly frog pond': ['/Users/karthikmahendra/Desktop/downloads/lilly frog pond/1.frog-lily-pond-2-b.jpg',
  '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/2.frog-2504507_960_720.jpg',
  '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/3.Frog-on-lily-pad.jpg',
  '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/4.9a49083d4d7458a194a451eea757a444.jpg',
  '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/5.Frog-Pond-Lily-Pad-Water-Nature-Animal-4336943.jpg']}

At time of writing at least a few do, but since the Internet changes - it is possible your 5 won't. You can easily verify yourself, and (once you have working code) increase the number of images you pull to be more sure of getting a frog. Your goal is to validly run ResNet50 on the input images - don't worry about tuning or improving the model.

*Hint* - ResNet 50 doesn't just return "frog". The three labels it has for frogs are: `bullfrog, tree frog, tailed frog`

*Stretch goals* 
- Check for fish or other labels
- Create a matplotlib visualizations of the images and your prediction as the visualization label

In [69]:
# You've got something to do in this cell. ;)

import numpy as np

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions

def process_img_path(img_path):
  return image.load_img(img_path, target_size=(224, 224))

def img_contains_frog(img):
    """ Scans image for Frogs
    
    Should return a boolean (True/False) if a frog is in the image.
    
    Inputs:
    ---------
    img:  Precrossed image ready for prediction. The `process_img_path` function should already be applied to the image. 
    
    Returns: 
    ---------
    frogs (boolean):  TRUE or FALSE - There are frogs in the image.
    
    """
    
            
    return None

In [70]:
image_list = absolute_image_paths[0]["lilly frog pond"]

In [71]:
image_list

['/Users/karthikmahendra/Desktop/downloads/lilly frog pond/1.frog-lily-pond-2-b.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/2.frog-2504507_960_720.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/3.Frog-on-lily-pad.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/4.9a49083d4d7458a194a451eea757a444.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/5.Frog-Pond-Lily-Pad-Water-Nature-Animal-4336943.jpg']

In [72]:
def resize_image(filename, new_width=224, new_height=224):
    pil_image = Image.open(filename)
    pil_image = ImageOps.fit(pil_image, (new_width, new_height), Image.ANTIALIAS)
    pil_image_rgb = pil_image.convert('RGB')
    pil_image_rgb.save(filename, format='JPEG', quality=90)
    return filename

In [73]:
images = [resize_image(image) for image in image_list]
images

['/Users/karthikmahendra/Desktop/downloads/lilly frog pond/1.frog-lily-pond-2-b.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/2.frog-2504507_960_720.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/3.Frog-on-lily-pad.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/4.9a49083d4d7458a194a451eea757a444.jpg',
 '/Users/karthikmahendra/Desktop/downloads/lilly frog pond/5.Frog-Pond-Lily-Pad-Water-Nature-Animal-4336943.jpg']

In [74]:
real_images = np.array([np.asarray(Image.open(image)) / 255 for image in images])

In [75]:
real_images.shape

(5, 224, 224, 3)

In [76]:
print(f'sample frog image values: \n {real_images[0]}')

sample frog image values: 
 [[[0.49803922 0.56078431 0.17647059]
  [0.50196078 0.57254902 0.18431373]
  [0.50588235 0.57254902 0.20392157]
  ...
  [0.19607843 0.33333333 0.30588235]
  [0.2        0.3372549  0.31372549]
  [0.20392157 0.34509804 0.32941176]]

 [[0.48627451 0.52156863 0.19607843]
  [0.49803922 0.54901961 0.20392157]
  [0.48627451 0.54509804 0.18823529]
  ...
  [0.23529412 0.35294118 0.34509804]
  [0.22352941 0.34509804 0.35294118]
  [0.20784314 0.3372549  0.35686275]]

 [[0.51372549 0.52941176 0.2       ]
  [0.49803922 0.53333333 0.17647059]
  [0.47058824 0.51764706 0.13333333]
  ...
  [0.2        0.30588235 0.27058824]
  [0.21176471 0.3254902  0.31764706]
  [0.22745098 0.3372549  0.34901961]]

 ...

 [[0.08627451 0.09019608 0.09803922]
  [0.15686275 0.16078431 0.09803922]
  [0.34509804 0.34901961 0.18431373]
  ...
  [0.03529412 0.10588235 0.16078431]
  [0.03529412 0.09803922 0.15686275]
  [0.03529412 0.09803922 0.15686275]]

 [[0.06666667 0.08235294 0.09411765]
  [0.0509

In [79]:
Y = [1] * len (real_images)
Y = np.asarray(Y)
Y = Y.reshape(5,1)

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(real_images, Y, test_size=0.25)

In [83]:
res = ResNet50(input_shape=(224, 224,3), weights='imagenet', include_top=False)

In [84]:
# make all resnet layers untrainable
for layer in res.layers:
    layer.trainable = False

In [ ]:
x = res.output
x = GlobalAveragePooling2D()(x)
predictions = Dense(1, activation='sigmoid')(x)
model = Model(res.input, predictions)

In [86]:
x = res.output
x = GlobalAveragePooling2D()(x)
predictions = Dense(1, activation='sigmoid')(x)
model = Model(res.input, predictions)

In [87]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [88]:
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test));

Train on 3 samples, validate on 2 samples
Epoch 1/5
3/3 [==============================] - 4s 1s/sample - loss: 0.3565 - accuracy: 1.0000 - val_loss: 0.3413 - val_accuracy: 1.0000
Epoch 2/5
3/3 [==============================] - 1s 185ms/sample - loss: 0.1714 - accuracy: 1.0000 - val_loss: 0.2818 - val_accuracy: 1.0000
Epoch 3/5
3/3 [==============================] - 1s 179ms/sample - loss: 0.0821 - accuracy: 1.0000 - val_loss: 0.2357 - val_accuracy: 1.0000
Epoch 4/5
3/3 [==============================] - 1s 176ms/sample - loss: 0.0412 - accuracy: 1.0000 - val_loss: 0.2004 - val_accuracy: 1.0000
Epoch 5/5
3/3 [==============================] - 1s 184ms/sample - loss: 0.0221 - accuracy: 1.0000 - val_loss: 0.1731 - val_accuracy: 1.0000


In [90]:
acc = model.evaluate(X_test, y_test, verbose=0)
acc

[0.17309622466564178, 1.0]

##Accuracy 1 implies theere is a frog in the image? 

#### Stretch Goal: Displaying Predictions

In [1]:
import matplotlib.pyplot as plt



<a id="p3"></a>
## Part 3 - Autoencoders

Describe a use case for an autoencoder given that an autoencoder tries to predict its own input. 

Autoencoder is an unsupervised artificial neural network that learns how to efficiently compress and encode data then learns how to reconstruct the data back from the reduced encoded representation to a representation that is as close to the original input as possible.
Autoencoder, by design, reduces data dimensions by learning how to ignore the noise in the data.

<a id="p4"></a>
## Part 4 - More...

Answer the following questions, with a target audience of a fellow Data Scientist:

- What do you consider your strongest area, as a Data Scientist?
Not sure yet 🤷🏻‍♂️, but I think I am good at 
- What area of Data Science would you most like to learn more about, and why?
NLP, since I want to work on voice assistants
- Where do you think Data Science will be in 5 years?
I think it will have have an application in every industry, just as software has entered into every industry today.
- What are the threats posed by AI to our society?
I think its mainly Bias, if AI is mimicking human brains on steroids, its also going to amplify human bias which exists in all of us.  
- How do you think we can counteract those threats? 
Continually monitor bias, do extensive testing before deploying models that affect human lives. Diveristy ? since inputs from various people might help avoid implicit biases that are sometimes invisible to us. 
- Do you think achieving General Artifical Intelligence is ever possible?
Probably not in my lifetime. (Having said that with advances in science I might live for like 200 years, in which case i think AGI might be a thing!)

A few sentences per answer is fine - only elaborate if time allows.

## Congratulations! 

Thank you for your hard work, and congratulations! You've learned a lot, and you should proudly call yourself a Data Scientist.


In [ ]:
from IPython.display import HTML

HTML("""<iframe src="https://giphy.com/embed/26xivLqkv86uJzqWk" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/mumm-champagne-saber-26xivLqkv86uJzqWk">via GIPHY</a></p>""")